#! /usr/bin/env python
import os
from return_directories import return_directories


def black_scores():
    print("black formatting Scores ...")
    for score in return_directories():
        print(f"Formatting {score.name} ...")
        os.system(f"black-reformat-local {score}")
        print()

if __name__ == "__main__":
    black_scores()
