#! /usr/bin/env python
import os
from return_directories import return_directories


def black_check():
    print("black checking Scores ...")
    for score in return_directories():
        print(f"Checking {score.name} ...")
        os.system(f"black-check-local {score}")
        print()

if __name__ == "__main__":
    black_check()
