#! /usr/bin/env python
import os
from return_directories import return_directories


def flake8_check():
    print("isort checking Scores ...")
    for score in return_directories():
        print(f"Checking {score.name} ...")
        os.system(f"flake8-check-local {score}")
        print()

if __name__ == "__main__":
    flake8_check()
