#! /usr/bin/env python
import os
from return_directories import return_directories


def isort_reformat():
    print("isort formatting Scores ...")
    for score in return_directories():
        print(f"Formatting {score.name} ...")
        os.system(f"isort-reformat-local {score}")
        print()

if __name__ == "__main__":
    isort_reformat()
