#! /usr/bin/env python
import pathlib
import subprocess

from return_directories import return_directories


def execute_shell_command(cmd, repo_dir):
    pipe = subprocess.Popen(
        cmd, cwd=repo_dir, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    bytes = pipe.stdout.read()
    string = bytes.decode("utf-8")
    print(string)
    pipe.wait()

def git_status(repo_dir):
    cmd = "git status ."
    execute_shell_command(cmd, repo_dir)

def st_scores():
    for score in return_directories():
        print(f"Examining {score.name} ...")
        print()
        score = str(score)
        git_status(score)
        print("#########")

if __name__ == "__main__":
    st_scores()
