#! /usr/bin/env python
import os
import pathlib
import sys


def mypy_check(wrapper_path):
    dir = pathlib.Path(wrapper_path).absolute()
    contents_path = dir / dir.name
    for sub_dir in sorted(contents_path.iterdir()):
        if sub_dir.name == "segments":
            for segment_dir in sorted(sub_dir.iterdir()):
                if segment_dir.name.startswith("_"):
                    continue
                if segment_dir.name.startswith("."):
                    continue
                else:
                    print(f"Mypy checking {segment_dir.name} ...")
                    os.system(f"mypy {segment_dir}")
        else:
            if sub_dir.name.startswith("_"):
                continue
            if sub_dir.name.startswith("."):
                continue
            if sub_dir.name == "audio":
                continue
            if sub_dir.name == "build":
                continue
            if sub_dir.name == "Build":
                continue
            if sub_dir.name == "Covers":
                continue
            if sub_dir.name == "distribution":
                continue
            if sub_dir.name == "Distribution":
                continue
            if sub_dir.name == "dotfiles":
                continue
            if sub_dir.name == "etc":
                continue
            if sub_dir.name == "research":
                continue
            print(f"Mypy checking {sub_dir} ...")
            os.system(f"mypy {sub_dir}")

if __name__ == "__main__":
    wrapper = sys.argv[1]
    mypy_check(wrapper)
