#! /usr/bin/env python
import pathlib
import subprocess

from return_directories import return_directories


def execute_shell_command(cmd, work_dir):
    pipe = subprocess.Popen(
        cmd, shell=True, cwd=work_dir, stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    bytes = pipe.stdout.read()
    string = bytes.decode("utf-8")
    print(string)
    pipe.wait()


def git_add(file_path, repo_dir):
    cmd = "git add " + file_path
    execute_shell_command(cmd, repo_dir)


def git_commit(commit_message, repo_dir):
    cmd = 'git commit -am "%s"' % commit_message
    execute_shell_command(cmd, repo_dir)


def git_push(repo_dir):
    cmd = "git push "
    execute_shell_command(cmd, repo_dir)


def push_scores():
    print("Pushing Scores ...")
    message = input("Commit message: ")
    for score in return_directories():
        print(f"NOW HANDLING {score.name} ...")
        score = str(score)
        print("git adding ...")
        git_add(file_path=score, repo_dir=score)
        print("git committing ...")
        git_commit(commit_message=message, repo_dir=score)
        print("git pushing ...")
        git_push(score)
        print("#########")

if __name__ == "__main__":
    push_scores()
