name: testing

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

env:
  LILYPOND: /tmp/lilypond
  LILYPOND_URL: http://lilypond.org/download/binaries/linux-64/
  LILYPOND_SOURCE: lilypond-2.19.84-1.linux-64.sh
  ABJAD: /tmp/abjad
  RMAKERS: /tmp/abjad-ext-rmakers
  MICROTONES: /tmp/abjad-ext-microtones
  TSMAKERS: /tmp/tsmakers
  BACA: /tmp/baca
  IDE: /tmp/ide

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install checkers
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort pytest six

    - name: Install lilypond
      run: |
        wget -q -O $LILYPOND $LILYPOND_URL/$LILYPOND_SOURCE
        sh $LILYPOND --batch

    - name: Install abjad
      run: |
        git clone -b trevor/dev https://github.com/Abjad/abjad.git $ABJAD
        pip install -e $ABJAD
        echo "$ABJAD/scr" >> $GITHUB_PATH

    - name: Install rmakers
      run: |
        git clone https://github.com/Abjad/abjad-ext-rmakers.git $RMAKERS
        pip install -e $RMAKERS

    - name: Install microtones
      run: |
        git clone -b greg/dev https://github.com/GregoryREvans/abjad-ext-microtones.git $MICROTONES
        pip install -e $MICROTONES

    - name: Install tsmakers
      run: |
        git clone https://github.com/GregoryREvans/tsmakers.git $TSMAKERS
        pip install -e $TSMAKERS

    - name: Install baca
      run: |
        git clone https://github.com/trevorbaca/baca.git $BACA
        pip install -e $BACA

    - name: Install ide
      run: |
        git clone https://github.com/trevorbaca/ide.git $IDE
        pip install -e $IDE

    - name: Install package
      run: |
        pip install -e .
        echo "./scr" >> $GITHUB_PATH

    - name: Sanity-check
      run: |
        ls
        which black-check
        which evans-doctest
        which flake8-check
        which isort-check
        python -c 'import evans'

    - name: Run checkers
      run: |
        black-check .
        flake8-check .
        isort-check .
        evans-doctest .
